// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum LogLevel
{
	Trace("f8f2d1b3-22d6-4810-a2fe-b7e556f8ac06"),
	Debug("7fd1a466-7f24-41a7-86c7-e09c5ab603ef"),
	Info("2f97a708-da7e-4d9a-a57b-55350f2cc195"),
	Warning("f0f2928c-93b6-4f69-98df-f2316043c8ce"),
	Error("7e55283d-aca7-4001-b319-72311ea01140"),
	Critical("9a51efa8-d25a-4af1-a180-76c0f81762ab");

	private final java.lang.String i18nCaptionKey;
	
	private LogLevel(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
