// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum SanitizerPolicy
{
	BLOCKS("8471e57c-5c15-4ee9-a498-f973a3183fd3"),
	FORMATTING("8845c0dc-e276-49ba-bf31-0a499bbd757d"),
	IMAGES("43c777bf-ab2a-476e-a716-d55074bfa6a5"),
	LINKS("fda87513-857e-4b21-8e2c-84670ef9d131"),
	STYLES("d90bf0f3-6b28-452b-81c9-493dd943870c"),
	TABLES("0c3be1c5-d6b6-4218-9e48-43feae6f4022");

	private final java.lang.String i18nCaptionKey;
	
	private SanitizerPolicy(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
