// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum StandardEncodings
{
	US_ASCII("0d53cd18-9a77-493a-9af5-18ac29a559de"),
	ISO_8859_1("b1f15b25-3887-4c4e-83cb-81eecd2f24c6"),
	UTF_8("78b93329-21fc-4461-9dcc-2da328923ce2"),
	UTF_16BE("71d7bdf4-cf54-4cd2-8dbe-4ec4df1c106b"),
	UTF_16LE("87c221a1-348d-4c9b-a798-dee5bc1699f8"),
	UTF_16("e78e5f52-7887-4910-9413-b90e85c6d3fd");

	private final java.lang.String i18nCaptionKey;
	
	private StandardEncodings(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
