// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum StandardEncodings
{
	US_ASCII("1075932c-ecbf-4fcc-97b1-32333daace4b"),
	ISO_8859_1("ae1736c7-f0b5-4e3b-b857-6cab6af64742"),
	UTF_8("57a7b0cd-17f6-4759-9f67-23516f0049fc"),
	UTF_16BE("88496c4d-983e-43e2-8a78-1683f813a49d"),
	UTF_16LE("f633d174-7048-4d4c-a659-dc8f2ae9910d"),
	UTF_16("84bf7e29-db2c-4937-a91a-5508271c4e2c");

	private final java.lang.String i18nCaptionKey;
	
	private StandardEncodings(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
