// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommons.proxies;

public enum GeocodingProvider
{
	Google("b6a87b4e-d53a-41bd-bc95-da918ce0d900"),
	Geocodio("5250c6e2-c87c-47b2-8c26-40506f413092"),
	LocationIQ("943186a6-a1d9-49bf-b81a-98edc45ee499"),
	MapQuest("27ec0657-21ab-44a0-a2a1-5b28e62ce5d6");

	private final java.lang.String i18nCaptionKey;
	
	private GeocodingProvider(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
