// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testsimplelistwidget.proxies;

public enum AxisType
{
	SalesRepresentative("90b70a8d-8d9e-4d31-88e3-180d825a5077"),
	Location("56c178c7-210e-4ba1-be8e-3b38022f6e1f"),
	Customer("371f24c1-ec31-4648-a964-eea09a6ff9cf"),
	Item("75b1be53-4e05-4fb2-94d4-6bf5a45d1792");

	private final java.lang.String i18nCaptionKey;
	
	private AxisType(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
