// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testsimplelistwidget.proxies;

public enum QueryAction
{
	count("f400ddb6-017f-4a39-a516-8b8ea888fee9"),
	total_quantity("b560ab3f-7d3e-4c07-9668-a551a0014826"),
	total_amount("00ecf25f-7903-4312-9a4c-9d3ae79bae49"),
	list_quantities("55ce844f-dec0-4d45-ad6e-57f7eb6f88a7"),
	list_amounts("70f126a7-d3d6-4bd6-acc1-cf8609f80183");

	private final java.lang.String i18nCaptionKey;
	
	private QueryAction(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
