// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testsimplelistwidget.proxies;

public class SalesRepresentative
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject salesRepresentativeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TestSimpleListWidget.SalesRepresentative";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		RecordID("RecordID");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SalesRepresentative(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TestSimpleListWidget.SalesRepresentative"));
	}

	protected SalesRepresentative(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject salesRepresentativeMendixObject)
	{
		if (salesRepresentativeMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("TestSimpleListWidget.SalesRepresentative", salesRepresentativeMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TestSimpleListWidget.SalesRepresentative");

		this.salesRepresentativeMendixObject = salesRepresentativeMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'SalesRepresentative.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static testsimplelistwidget.proxies.SalesRepresentative initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return testsimplelistwidget.proxies.SalesRepresentative.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static testsimplelistwidget.proxies.SalesRepresentative initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new testsimplelistwidget.proxies.SalesRepresentative(context, mendixObject);
	}

	public static testsimplelistwidget.proxies.SalesRepresentative load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return testsimplelistwidget.proxies.SalesRepresentative.initialize(context, mendixObject);
	}

	public static java.util.List<testsimplelistwidget.proxies.SalesRepresentative> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<testsimplelistwidget.proxies.SalesRepresentative> result = new java.util.ArrayList<testsimplelistwidget.proxies.SalesRepresentative>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//TestSimpleListWidget.SalesRepresentative" + xpathConstraint))
			result.add(testsimplelistwidget.proxies.SalesRepresentative.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of RecordID
	 */
	public final java.lang.Long getRecordID()
	{
		return getRecordID(getContext());
	}

	/**
	 * @param context
	 * @return value of RecordID
	 */
	public final java.lang.Long getRecordID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.RecordID.toString());
	}

	/**
	 * Set value of RecordID
	 * @param recordid
	 */
	public final void setRecordID(java.lang.Long recordid)
	{
		setRecordID(getContext(), recordid);
	}

	/**
	 * Set value of RecordID
	 * @param context
	 * @param recordid
	 */
	public final void setRecordID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long recordid)
	{
		getMendixObject().setValue(context, MemberNames.RecordID.toString(), recordid);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return salesRepresentativeMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final testsimplelistwidget.proxies.SalesRepresentative that = (testsimplelistwidget.proxies.SalesRepresentative) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TestSimpleListWidget.SalesRepresentative";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
