// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testsimplelistwidget.proxies;

public class UserContext
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject userContextMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TestSimpleListWidget.UserContext";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ContextGuid("ContextGuid"),
		FromDate("FromDate"),
		ToDate("ToDate"),
		SplitPanePosition("SplitPanePosition"),
		MoreData("MoreData"),
		UserContext_SalesRepresentative("TestSimpleListWidget.UserContext_SalesRepresentative"),
		UserContext_Location("TestSimpleListWidget.UserContext_Location"),
		UserContext_Customer("TestSimpleListWidget.UserContext_Customer"),
		UserContext_Item("TestSimpleListWidget.UserContext_Item"),
		UserContext_SalesOrder_Selected("TestSimpleListWidget.UserContext_SalesOrder_Selected"),
		UserContext_SalesOrder_List("TestSimpleListWidget.UserContext_SalesOrder_List"),
		UserContext_Session("TestSimpleListWidget.UserContext_Session");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public UserContext(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TestSimpleListWidget.UserContext"));
	}

	protected UserContext(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject userContextMendixObject)
	{
		if (userContextMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("TestSimpleListWidget.UserContext", userContextMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TestSimpleListWidget.UserContext");

		this.userContextMendixObject = userContextMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'UserContext.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static testsimplelistwidget.proxies.UserContext initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return testsimplelistwidget.proxies.UserContext.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static testsimplelistwidget.proxies.UserContext initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new testsimplelistwidget.proxies.UserContext(context, mendixObject);
	}

	public static testsimplelistwidget.proxies.UserContext load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return testsimplelistwidget.proxies.UserContext.initialize(context, mendixObject);
	}

	public static java.util.List<testsimplelistwidget.proxies.UserContext> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<testsimplelistwidget.proxies.UserContext> result = new java.util.ArrayList<testsimplelistwidget.proxies.UserContext>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//TestSimpleListWidget.UserContext" + xpathConstraint))
			result.add(testsimplelistwidget.proxies.UserContext.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ContextGuid
	 */
	public final java.lang.Long getContextGuid()
	{
		return getContextGuid(getContext());
	}

	/**
	 * @param context
	 * @return value of ContextGuid
	 */
	public final java.lang.Long getContextGuid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.ContextGuid.toString());
	}

	/**
	 * Set value of ContextGuid
	 * @param contextguid
	 */
	public final void setContextGuid(java.lang.Long contextguid)
	{
		setContextGuid(getContext(), contextguid);
	}

	/**
	 * Set value of ContextGuid
	 * @param context
	 * @param contextguid
	 */
	public final void setContextGuid(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long contextguid)
	{
		getMendixObject().setValue(context, MemberNames.ContextGuid.toString(), contextguid);
	}

	/**
	 * @return value of FromDate
	 */
	public final java.util.Date getFromDate()
	{
		return getFromDate(getContext());
	}

	/**
	 * @param context
	 * @return value of FromDate
	 */
	public final java.util.Date getFromDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.FromDate.toString());
	}

	/**
	 * Set value of FromDate
	 * @param fromdate
	 */
	public final void setFromDate(java.util.Date fromdate)
	{
		setFromDate(getContext(), fromdate);
	}

	/**
	 * Set value of FromDate
	 * @param context
	 * @param fromdate
	 */
	public final void setFromDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date fromdate)
	{
		getMendixObject().setValue(context, MemberNames.FromDate.toString(), fromdate);
	}

	/**
	 * @return value of ToDate
	 */
	public final java.util.Date getToDate()
	{
		return getToDate(getContext());
	}

	/**
	 * @param context
	 * @return value of ToDate
	 */
	public final java.util.Date getToDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ToDate.toString());
	}

	/**
	 * Set value of ToDate
	 * @param todate
	 */
	public final void setToDate(java.util.Date todate)
	{
		setToDate(getContext(), todate);
	}

	/**
	 * Set value of ToDate
	 * @param context
	 * @param todate
	 */
	public final void setToDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date todate)
	{
		getMendixObject().setValue(context, MemberNames.ToDate.toString(), todate);
	}

	/**
	 * @return value of SplitPanePosition
	 */
	public final java.lang.Integer getSplitPanePosition()
	{
		return getSplitPanePosition(getContext());
	}

	/**
	 * @param context
	 * @return value of SplitPanePosition
	 */
	public final java.lang.Integer getSplitPanePosition(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.SplitPanePosition.toString());
	}

	/**
	 * Set value of SplitPanePosition
	 * @param splitpaneposition
	 */
	public final void setSplitPanePosition(java.lang.Integer splitpaneposition)
	{
		setSplitPanePosition(getContext(), splitpaneposition);
	}

	/**
	 * Set value of SplitPanePosition
	 * @param context
	 * @param splitpaneposition
	 */
	public final void setSplitPanePosition(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer splitpaneposition)
	{
		getMendixObject().setValue(context, MemberNames.SplitPanePosition.toString(), splitpaneposition);
	}

	/**
	 * @return value of MoreData
	 */
	public final java.lang.Boolean getMoreData()
	{
		return getMoreData(getContext());
	}

	/**
	 * @param context
	 * @return value of MoreData
	 */
	public final java.lang.Boolean getMoreData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.MoreData.toString());
	}

	/**
	 * Set value of MoreData
	 * @param moredata
	 */
	public final void setMoreData(java.lang.Boolean moredata)
	{
		setMoreData(getContext(), moredata);
	}

	/**
	 * Set value of MoreData
	 * @param context
	 * @param moredata
	 */
	public final void setMoreData(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean moredata)
	{
		getMendixObject().setValue(context, MemberNames.MoreData.toString(), moredata);
	}

	/**
	 * @return value of UserContext_SalesRepresentative
	 */
	public final testsimplelistwidget.proxies.SalesRepresentative getUserContext_SalesRepresentative() throws com.mendix.core.CoreException
	{
		return getUserContext_SalesRepresentative(getContext());
	}

	/**
	 * @param context
	 * @return value of UserContext_SalesRepresentative
	 */
	public final testsimplelistwidget.proxies.SalesRepresentative getUserContext_SalesRepresentative(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		testsimplelistwidget.proxies.SalesRepresentative result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.UserContext_SalesRepresentative.toString());
		if (identifier != null)
			result = testsimplelistwidget.proxies.SalesRepresentative.load(context, identifier);
		return result;
	}

	/**
	 * Set value of UserContext_SalesRepresentative
	 * @param usercontext_salesrepresentative
	 */
	public final void setUserContext_SalesRepresentative(testsimplelistwidget.proxies.SalesRepresentative usercontext_salesrepresentative)
	{
		setUserContext_SalesRepresentative(getContext(), usercontext_salesrepresentative);
	}

	/**
	 * Set value of UserContext_SalesRepresentative
	 * @param context
	 * @param usercontext_salesrepresentative
	 */
	public final void setUserContext_SalesRepresentative(com.mendix.systemwideinterfaces.core.IContext context, testsimplelistwidget.proxies.SalesRepresentative usercontext_salesrepresentative)
	{
		if (usercontext_salesrepresentative == null)
			getMendixObject().setValue(context, MemberNames.UserContext_SalesRepresentative.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.UserContext_SalesRepresentative.toString(), usercontext_salesrepresentative.getMendixObject().getId());
	}

	/**
	 * @return value of UserContext_Location
	 */
	public final testsimplelistwidget.proxies.Location getUserContext_Location() throws com.mendix.core.CoreException
	{
		return getUserContext_Location(getContext());
	}

	/**
	 * @param context
	 * @return value of UserContext_Location
	 */
	public final testsimplelistwidget.proxies.Location getUserContext_Location(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		testsimplelistwidget.proxies.Location result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.UserContext_Location.toString());
		if (identifier != null)
			result = testsimplelistwidget.proxies.Location.load(context, identifier);
		return result;
	}

	/**
	 * Set value of UserContext_Location
	 * @param usercontext_location
	 */
	public final void setUserContext_Location(testsimplelistwidget.proxies.Location usercontext_location)
	{
		setUserContext_Location(getContext(), usercontext_location);
	}

	/**
	 * Set value of UserContext_Location
	 * @param context
	 * @param usercontext_location
	 */
	public final void setUserContext_Location(com.mendix.systemwideinterfaces.core.IContext context, testsimplelistwidget.proxies.Location usercontext_location)
	{
		if (usercontext_location == null)
			getMendixObject().setValue(context, MemberNames.UserContext_Location.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.UserContext_Location.toString(), usercontext_location.getMendixObject().getId());
	}

	/**
	 * @return value of UserContext_Customer
	 */
	public final testsimplelistwidget.proxies.Customer getUserContext_Customer() throws com.mendix.core.CoreException
	{
		return getUserContext_Customer(getContext());
	}

	/**
	 * @param context
	 * @return value of UserContext_Customer
	 */
	public final testsimplelistwidget.proxies.Customer getUserContext_Customer(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		testsimplelistwidget.proxies.Customer result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.UserContext_Customer.toString());
		if (identifier != null)
			result = testsimplelistwidget.proxies.Customer.load(context, identifier);
		return result;
	}

	/**
	 * Set value of UserContext_Customer
	 * @param usercontext_customer
	 */
	public final void setUserContext_Customer(testsimplelistwidget.proxies.Customer usercontext_customer)
	{
		setUserContext_Customer(getContext(), usercontext_customer);
	}

	/**
	 * Set value of UserContext_Customer
	 * @param context
	 * @param usercontext_customer
	 */
	public final void setUserContext_Customer(com.mendix.systemwideinterfaces.core.IContext context, testsimplelistwidget.proxies.Customer usercontext_customer)
	{
		if (usercontext_customer == null)
			getMendixObject().setValue(context, MemberNames.UserContext_Customer.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.UserContext_Customer.toString(), usercontext_customer.getMendixObject().getId());
	}

	/**
	 * @return value of UserContext_Item
	 */
	public final testsimplelistwidget.proxies.Item getUserContext_Item() throws com.mendix.core.CoreException
	{
		return getUserContext_Item(getContext());
	}

	/**
	 * @param context
	 * @return value of UserContext_Item
	 */
	public final testsimplelistwidget.proxies.Item getUserContext_Item(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		testsimplelistwidget.proxies.Item result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.UserContext_Item.toString());
		if (identifier != null)
			result = testsimplelistwidget.proxies.Item.load(context, identifier);
		return result;
	}

	/**
	 * Set value of UserContext_Item
	 * @param usercontext_item
	 */
	public final void setUserContext_Item(testsimplelistwidget.proxies.Item usercontext_item)
	{
		setUserContext_Item(getContext(), usercontext_item);
	}

	/**
	 * Set value of UserContext_Item
	 * @param context
	 * @param usercontext_item
	 */
	public final void setUserContext_Item(com.mendix.systemwideinterfaces.core.IContext context, testsimplelistwidget.proxies.Item usercontext_item)
	{
		if (usercontext_item == null)
			getMendixObject().setValue(context, MemberNames.UserContext_Item.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.UserContext_Item.toString(), usercontext_item.getMendixObject().getId());
	}

	/**
	 * @return value of UserContext_SalesOrder_Selected
	 */
	public final testsimplelistwidget.proxies.SalesOrder getUserContext_SalesOrder_Selected() throws com.mendix.core.CoreException
	{
		return getUserContext_SalesOrder_Selected(getContext());
	}

	/**
	 * @param context
	 * @return value of UserContext_SalesOrder_Selected
	 */
	public final testsimplelistwidget.proxies.SalesOrder getUserContext_SalesOrder_Selected(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		testsimplelistwidget.proxies.SalesOrder result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.UserContext_SalesOrder_Selected.toString());
		if (identifier != null)
			result = testsimplelistwidget.proxies.SalesOrder.load(context, identifier);
		return result;
	}

	/**
	 * Set value of UserContext_SalesOrder_Selected
	 * @param usercontext_salesorder_selected
	 */
	public final void setUserContext_SalesOrder_Selected(testsimplelistwidget.proxies.SalesOrder usercontext_salesorder_selected)
	{
		setUserContext_SalesOrder_Selected(getContext(), usercontext_salesorder_selected);
	}

	/**
	 * Set value of UserContext_SalesOrder_Selected
	 * @param context
	 * @param usercontext_salesorder_selected
	 */
	public final void setUserContext_SalesOrder_Selected(com.mendix.systemwideinterfaces.core.IContext context, testsimplelistwidget.proxies.SalesOrder usercontext_salesorder_selected)
	{
		if (usercontext_salesorder_selected == null)
			getMendixObject().setValue(context, MemberNames.UserContext_SalesOrder_Selected.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.UserContext_SalesOrder_Selected.toString(), usercontext_salesorder_selected.getMendixObject().getId());
	}

	/**
	 * @return value of UserContext_SalesOrder_List
	 */
	public final java.util.List<testsimplelistwidget.proxies.SalesOrder> getUserContext_SalesOrder_List() throws com.mendix.core.CoreException
	{
		return getUserContext_SalesOrder_List(getContext());
	}

	/**
	 * @param context
	 * @return value of UserContext_SalesOrder_List
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<testsimplelistwidget.proxies.SalesOrder> getUserContext_SalesOrder_List(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<testsimplelistwidget.proxies.SalesOrder> result = new java.util.ArrayList<testsimplelistwidget.proxies.SalesOrder>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.UserContext_SalesOrder_List.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(testsimplelistwidget.proxies.SalesOrder.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of UserContext_SalesOrder_List
	 * @param usercontext_salesorder_list
	 */
	public final void setUserContext_SalesOrder_List(java.util.List<testsimplelistwidget.proxies.SalesOrder> usercontext_salesorder_list)
	{
		setUserContext_SalesOrder_List(getContext(), usercontext_salesorder_list);
	}

	/**
	 * Set value of UserContext_SalesOrder_List
	 * @param context
	 * @param usercontext_salesorder_list
	 */
	public final void setUserContext_SalesOrder_List(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<testsimplelistwidget.proxies.SalesOrder> usercontext_salesorder_list)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (testsimplelistwidget.proxies.SalesOrder proxyObject : usercontext_salesorder_list)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.UserContext_SalesOrder_List.toString(), identifiers);
	}

	/**
	 * @return value of UserContext_Session
	 */
	public final system.proxies.Session getUserContext_Session() throws com.mendix.core.CoreException
	{
		return getUserContext_Session(getContext());
	}

	/**
	 * @param context
	 * @return value of UserContext_Session
	 */
	public final system.proxies.Session getUserContext_Session(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.Session result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.UserContext_Session.toString());
		if (identifier != null)
			result = system.proxies.Session.load(context, identifier);
		return result;
	}

	/**
	 * Set value of UserContext_Session
	 * @param usercontext_session
	 */
	public final void setUserContext_Session(system.proxies.Session usercontext_session)
	{
		setUserContext_Session(getContext(), usercontext_session);
	}

	/**
	 * Set value of UserContext_Session
	 * @param context
	 * @param usercontext_session
	 */
	public final void setUserContext_Session(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.Session usercontext_session)
	{
		if (usercontext_session == null)
			getMendixObject().setValue(context, MemberNames.UserContext_Session.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.UserContext_Session.toString(), usercontext_session.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return userContextMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final testsimplelistwidget.proxies.UserContext that = (testsimplelistwidget.proxies.UserContext) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TestSimpleListWidget.UserContext";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
