// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testsimplelistwidget.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the TestSimpleListWidget module
	public static testsimplelistwidget.proxies.UserContext dS_UserContext(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("TestSimpleListWidget.DS_UserContext").withParams(params).execute(context);
		return result == null ? null : testsimplelistwidget.proxies.UserContext.initialize(context, result);
	}
	public static void oCh_UserContext_Refresh(IContext context, testsimplelistwidget.proxies.UserContext _userContext)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("UserContext", _userContext == null ? null : _userContext.getMendixObject());
		Core.microflowCall("TestSimpleListWidget.OCh_UserContext_Refresh").withParams(params).execute(context);
	}
	public static void oCh_UserContext_SplitPosition(IContext context, testsimplelistwidget.proxies.UserContext _userContext)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("UserContext", _userContext == null ? null : _userContext.getMendixObject());
		Core.microflowCall("TestSimpleListWidget.OCh_UserContext_SplitPosition").withParams(params).execute(context);
	}
	public static testsimplelistwidget.proxies.UserContext sUB_UserContext_GetOrCreate(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("TestSimpleListWidget.SUB_UserContext_GetOrCreate").withParams(params).execute(context);
		return result == null ? null : testsimplelistwidget.proxies.UserContext.initialize(context, result);
	}
	public static void sUB_UserContext_RefreshList(IContext context, testsimplelistwidget.proxies.UserContext _userContext)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("UserContext", _userContext == null ? null : _userContext.getMendixObject());
		Core.microflowCall("TestSimpleListWidget.SUB_UserContext_RefreshList").withParams(params).execute(context);
	}
	public static boolean sUB_UserContext_Validate(IContext context, testsimplelistwidget.proxies.UserContext _userContext)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("UserContext", _userContext == null ? null : _userContext.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("TestSimpleListWidget.SUB_UserContext_Validate").withParams(params).execute(context);
	}
}