// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("673c308f-7323-4e77-ad33-a1d489938e1b"),
	startsWith("4ae5683a-165d-4822-a430-67387833856b"),
	endsWith("68a81c4b-8c4f-49d4-92e6-ae347315cce6"),
	between("796d1c60-e849-42de-abcc-d388f52800da"),
	greater("ed089def-c192-44b3-8431-76f4f1201630"),
	greaterEqual("0a3a3d1b-3c6a-4901-b884-5899884bf5a5"),
	equal("e02239e7-f941-4435-bbbe-4b480aec3a55"),
	notEqual("340fdec4-4bf3-4fdc-9fac-b7a5fb285fbd"),
	smaller("7d230854-ec10-4987-881a-193f5770961e"),
	smallerEqual("66b07caf-5097-44e7-b39b-2e91ccc04663"),
	empty("3c8ff8d2-9fce-41d3-894d-d3d2d569cd99"),
	notEmpty("93033ac3-e8e9-4b7f-90cb-c221a7bfb680");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
