// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("752a25e3-60aa-4147-8b26-6e2a9de17d60"),
	startsWith("33f51611-4407-449b-9298-8d715dd16395"),
	endsWith("1d788615-3263-4bd6-9fee-262e3cb33d74"),
	between("6fc9adf7-432b-43a6-b004-7c598ea10c4c"),
	greater("7d78cb4e-c7d4-4dc9-910e-ffd242c5b214"),
	greaterEqual("62cadfea-cba3-44f8-98c2-8cfc87963ecc"),
	equal("65ee702b-38d1-47d9-bce3-32c8c126a7df"),
	notEqual("1a8e255b-f1f5-47df-a943-7a87cc33e269"),
	smaller("b142386f-10b9-4a77-a4ea-d5e295724e02"),
	smallerEqual("fddc3a75-3ecb-44aa-8372-a844af3e0f75"),
	empty("4c819ef5-c94a-457c-bd78-bd9560b6dac7"),
	notEmpty("bc757a5d-95e0-4e05-9d6f-8fdd2bb2fc60");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
